# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d0d3c800c3947d06a00fdae884c3b862b586e60ca4530e7678e31e5143516d3b5085862c1653ebaa5f3a0440b0492d94c5eccd8d608a4e624111b6f0d6bae7d

test:
  secret_key_base: 61faf7e5322b197d36c44359bac07f2476d7d3110d80dbb5d9f6c9fd946c15bc67bc66be986cd96fed9cd8ca9c0e5718994cb99a6ca32909066e1ee19d33ad54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
